### ISSUE TITLE
Flickity fade slide error

### ISSUE THREAD

**Issue by billpebert** [metafizzy/flickity-fade#18]
Please help, I got this error when using flickity-fade package (with cdn)

**Here is the css cdn package**

 `<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">`
 `<link rel="stylesheet" href="https://unpkg.com/flickity-fade@2/flickity-fade.css">`
 
 **Here is the carousel html and the script set up**
 `<div class="testimonial-carousel">`
  `    ....carousels div....`
 `</div>`
 
 `<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>`
 `<script src="https://unpkg.com/flickity-fade@2/flickity-fade.js"></script>`
 `<script>`
     `$('.testimonial-carousel').flickity({`
     `    // options`
         `fade: true,`
         `cellAlign: 'left',`
         `contain: true,`
         `prevNextButtons: false`
     `});`
 `</script>`

i don't figure out why this slide fade not working, only run in the dom like i am using normal flickity package but, it shown error like img below
<img width="348" alt="image" src="https://user-images.githubusercontent.com/70867121/165246199-7781dffa-3682-4dde-8dae-059df38b4ab1.png">

**Comment by atlamors** [comment]
+1

**Comment by billpebert** [comment]
Solved by using flickity-fade@1
