### ISSUE TITLE
Slight flicker (no pun intended) between last and first slide when looping.

### ISSUE THREAD

**Issue by 23d1** [metafizzy/flickity-fade#2]
There seems to be a slight flicker when looping from the last to the first slide. Any idea on how to alleviate the issue? Perhaps a pure CSS solution (that's how I did fading prior, but it also had a visual bug when looping).

**Test case:** https://codepen.io/desandro/pen/azqbop

**Comment by 23d1** [comment]
It now seems (after emptying my cache) that the issue has gone away. Sorry for the false alarm!

**Comment by desandro** [comment]
Thank you for reporting this issue and for following up.

**Comment by 23d1** [comment]
I guess it's technically still there if you rapidly tap/click to loop around, but seems to work fine if the transition to the last slide gets to finish before going around to the first slide.

**Comment by Geestig** [comment]
I had this issue when I was using WrapAround: true in my options. Even though this has no use when using flickity-fade if I'm not mistaken?

**Comment by desandro** [comment]
Closing as a duplicate of #1.
