### ISSUE TITLE
Flickity fade not working

### ISSUE THREAD

**Issue by natainditama** [metafizzy/flickity-fade#20]
Please help, I got this error when using flickity-fade package 

![gambar](https://user-images.githubusercontent.com/81244669/166335679-b5da7070-0f45-4047-abd8-57a984000d96.png)

My init
![gambar](https://user-images.githubusercontent.com/81244669/166335765-f9a587b7-7a13-4f7f-a766-27d5e7c5ce19.png)

Flickity work fine but fade in not working

**Comment by mapsteps** [comment]
Seems like flickity-fade (v2) doesn't work with the current stable version of flickity (v2.3.0). I tried flickity-fade v1 (https://github.com/metafizzy/flickity-fade/tags) and it works fine.

**Comment by Retroguru** [comment]
Thanks for resolution @MapSteps, it works. Hopefully, the version 2 will be officially fixed soon.
