### ISSUE TITLE
NPM Usage Question

### ISSUE THREAD

**Issue by celsowhite** [metafizzy/flickity-fade#3]
Hi, appreciate the work on this! I am a bit confused how to use this with standard webpack builds.

**Question**

If using `import Flickity from "flickity-fade"`. Can I initialize all of my flkty instances with that import and will they behave just like `import Flickity from "flickity"`.?

I ask because I'm using code splitting and would like to keep my instance imports the same across my application regardless of if they are using the slide or fade effect.

**Investigation**

From looking at [the code](https://github.com/metafizzy/flickity-fade/blob/master/flickity-fade.js) it appears you are requiring the main Flickity package and returning it. So we should technically be able to just use this package to initialize but I'd like to double check.

**Suggestion**

I would make [this section](https://github.com/metafizzy/flickity-fade#webpack--browserify) of the readme clearer for those users that want to use a combination of fade and slide effects across their site. I.E if a user is using a combination of fade and slide effects they have to install both packages but can initialize all instances with 'flickity-fade'.

**Comment by desandro** [comment]
> If using import Flickity from "flickity-fade". Can I initialize all of my flkty instances with that import and will they behave just like import Flickity from "flickity".?

Yes. `flickity-fade` has `flickity` as a dependency. So by importing `'flickity-fade'` you get the standard `flickity` package PLUS fade functionality from `flickity-fade`.

I appreciate the suggestion. Typically I lean to only the most straightforward examples, rather than trying to broach every edge case.

**Comment by celsowhite** [comment]
Thanks @desandro. Totally understand re: suggestion.
